# Generated by Django 5.2.8 on 2025-11-13 14:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChaveDeUtilizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome_usuario', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('Ativa', 'Ativa'), ('Inativa', 'Inativa'), ('Expirada', 'Expirada')], default='Ativa', max_length=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ultimo_uso', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Chave de Utilização',
                'verbose_name_plural': 'Chaves de Utilização',
            },
        ),
    ]
