# Generated by Django 5.2.8 on 2025-11-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManusAITask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('task_title', models.CharField(blank=True, max_length=500, null=True)),
                ('task_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('running', 'Em execução'), ('completed', 'Completa'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('stop_reason', models.CharField(blank=True, max_length=50, null=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('message', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('data_completa', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Manus AI Task',
                'verbose_name_plural': 'Manus AI Tasks',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
